[package]
name = "todo"
description = "Yet another minimal TODO app for your terminal."
version = "0.1.0"
authors = ["Misnad <>"]
edition = "2024"

[dependencies]
text-colorizer = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "4.0"
